version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  app:
    container_name: BE_DEV
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGODB_URL}
    ports:
      - 8080:8080
    external_links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local