version: "3.7"

networks:
  hfnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    networks:
      hfnet:
        ipv4_address: 192.168.1.5
  app:
    container_name: BE_DEV
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn dev'
    env_file: .env
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGODB_URL}
    ports:
      - 8080:8080
    networks:
      hfnet:
        ipv4_address: 192.168.1.4
    external_links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongo-data: